# Generated by Django 5.0 on 2024-03-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_answer_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
