# Generated by Django 5.0 on 2024-03-11 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_delete_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=None)),
                ('gender', models.SmallIntegerField(default=None)),
                ('emotion', models.CharField(choices=[('angry', 'Злість'), ('happy', 'Радість'), ('neutral', 'Нейтральність'), ('sad', 'Сум'), ('surprise', 'Здивованість')], default=None, max_length=20)),
                ('face_number', models.IntegerField(default=1)),
                ('image_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.imagefaces')),
            ],
        ),
    ]
