# Generated by Django 5.0 on 2024-03-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_imagefaces_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='emotion',
            field=models.CharField(choices=[('Чоловік', 'Чоловік'), ('Жінка', 'Жінка')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='identification',
            name='gender',
            field=models.CharField(choices=[('angry', 'Злість'), ('happy', 'Радість'), ('neutral', 'Нейтральність'), ('sad', 'Сум'), ('surprise', 'Здивованість')], default=None, max_length=20),
        ),
    ]
