# Generated by Django 5.0 on 2024-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_identification_emotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='emotion',
            field=models.CharField(blank=True, choices=[('angry', 'Злість'), ('happy', 'Радість'), ('neutral', 'Нейтральність'), ('sad', 'Сум'), ('surprise', 'Здивованість')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='gender',
            field=models.CharField(blank=True, choices=[('Чоловік', 'Чоловік'), ('Жінка', 'Жінка')], default=None, max_length=20, null=True),
        ),
    ]
