# Generated by Django 5.0 on 2024-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_identification_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefaces',
            name='img',
            field=models.ImageField(upload_to='C:\\Users\\maksp\\PycharmProjects\\face_recognision\\media\\faces_dataset'),
        ),
    ]
