# Generated by Django 5.0 on 2024-03-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_imagefaces_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='emotion',
            field=models.CharField(blank=True, choices=[('Злість', 'Злість'), ('Радість', 'Радість'), ('Нейтральність', 'Нейтральність'), ('Сум', 'Сум'), ('Здивованість', 'Здивованість')], default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
