# Generated by Django 5.0 on 2024-04-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_identification_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='age',
            field=models.CharField(blank=True, default='Не задано', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='emotion',
            field=models.CharField(blank=True, choices=[('Злість', 'Злість'), ('Радість', 'Радість'), ('Нейтральність', 'Нейтральність'), ('Сум', 'Сум'), ('Здивованість', 'Здивованість'), ('Не задано', 'Не задано')], default='Не задано', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='gender',
            field=models.CharField(blank=True, choices=[('Чоловік', 'Чоловік'), ('Жінка', 'Жінка'), ('Не задано', 'Не задано')], default='Не задано', max_length=20, null=True),
        ),
    ]
