# Generated by Django 5.0 on 2024-04-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_identification_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
