# Generated by Django 5.0 on 2024-10-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_identification_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefaces',
            name='img',
            field=models.ImageField(upload_to='C:\\Users\\maksim\\PycharmProjects\\face_recognision\\media\\faces_dataset'),
        ),
    ]
